#!/bin/bash

# Sean Szumlanski
# COP 3503, Fall 2017

# =========================
# SneakyQueens: test-all.sh
# =========================
# You can run this script at the command line like so:
#
#   bash test-all.sh
#
# For more details, see the assignment PDF.


for i in `seq 1 6`;
do
	echo -n "Checking TestCase0$i... "

	# Attempt to compile.
	javac SneakyQueens.java TestCase0$i.java 2> /dev/null
	compile_val=$?
	if [[ $compile_val != 0 ]]; then
		echo "fail (failed to compile)"
		continue
	fi

	# Run program. Capture return value to check whether it crashes.
	java TestCase0$i > myoutput0$i.txt 2> /dev/null
	execution_val=$?
	if [[ $execution_val != 0 ]]; then
		echo "fail (program crashed)"
		continue
	fi

	# Run diff and capture its return value.
	diff myoutput0$i.txt sample_output/TestCase0$i-output.txt > /dev/null
	diff_val=$?
	
	# Output results based on diff's return value.
	if  [[ $diff_val != 0 ]]; then
		echo "fail (output does not match)"
	else
		echo "PASS!"
	fi
done

# Clean up any lingering .class files.
rm *.class

# Clean up the output files generated by this script.
rm myoutput0*.txt

echo ""
echo "WHOA THERE! Before you submit your program, please be aware that these test"
echo "cases are not comprehensive. You should create additional test cases in order"
echo "to fully test the functionality of your program."
